### ISSUE TITLE
TypeError: value.map is not a function

### ISSUE THREAD

**Issue by hetramjanghu** [konarshankar07/magento2-cms-hero-image#1]
Magento Version:- 2.3.4

After saving page it should show the uploaded image and option to replace or delete Hero image.
but it gives error in console "TypeError: value.map is not a function == file-uploader.js:79"

**Comment by konarshankar07** [comment]
Hello @hetramjanghu ...
Thanks for opening the issue. I will fix the issue and update you

**Comment by konarshankar07** [comment]
This Task will be fixed under https://github.com/konarshankar07/magento2-cms-hero-image/issues/2 ticket

**Comment by konarshankar07** [comment]
This issue has been fixed. Please test and reopen the ticket if you are still able to reproduce
Thanks
